// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoDLbYozK8H3TOECvogSrvUmkLQvkbXtI',
    appId: '1:657232052630:web:aab8a5c4a66ab0e8921db7',
    messagingSenderId: '657232052630',
    projectId: 'gazeta-6aabf',
    authDomain: 'gazeta-6aabf.firebaseapp.com',
    storageBucket: 'gazeta-6aabf.appspot.com',
    measurementId: 'G-V9RKDS5RRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzA4n87QnhXheUszBCYzzLM91vV_wTojs',
    appId: '1:657232052630:android:ef94c40c7c924107921db7',
    messagingSenderId: '657232052630',
    projectId: 'gazeta-6aabf',
    storageBucket: 'gazeta-6aabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEPVMOlC4sxDvrRgzyuJxp1NWo1RTQpY',
    appId: '1:657232052630:ios:756364feaf5b3562921db7',
    messagingSenderId: '657232052630',
    projectId: 'gazeta-6aabf',
    storageBucket: 'gazeta-6aabf.appspot.com',
    iosBundleId: 'com.example.gazeta',
  );
}
